service: royal-place-backend

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-south-1
  stage: dev
  environment:
    NODE_ENV: production
    MONGO_URI: ${env:MONGO_URI}

functions:
  api:
    handler: dist/handler.handler
    events:
      - httpApi: '*'

package:
  individually: true
  excludeDevDependencies: true

plugins:
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 4000
